---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: debian-7.8
    driver:
      box: chef/debian-7.8
      box_url: chef/debian-7.8
      network:
      - ["private_network", {ip: "192.168.156.25"}]
  - name: centos-6.6
    driver:
      box: chef/centos-6.6
      box_url: chef/centos-6.6
      network:
      - ["private_network", {ip: "192.168.156.24"}]

suites:
  - name: default
    data_bags_path: "test/integration/default/data_bags"
    encrypted_data_bag_secret_key_path: "test/integration/default/encrypted_data_bag_secret"
    run_list:
      - recipe[nginx_simple::server]
    attributes:
