name 'nginx_simple'
maintainer 'Michael Haas'
maintainer_email 'hmi@linux.com'
license 'apachev2'
description 'Installs/Configures Nginx via repositories'
long_description 'Installs/Configures Nginx via repositories. Provides configuration options for simple server and proxy functionality'
version '0.1.0'
depends 'yum', '~> 3.6.0'
depends 'apt', '~> 2.7.0'
depends 'certificate', '~> 1.0.0'
depends 'logrotate', '~> 1.9.1'

supports 'debian'
supports 'centos'
supports 'redhat'
supports 'amazon'
